#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MainMenu_PC

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Squad_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MainMenu_PC.BP_MainMenu_PC_C
// 0x0020 (0x0BC0 - 0x0BA0)
class ABP_MainMenu_PC_C final : public ASQPlayerController_Menu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void(class AMenuCamPawn_C* NewMenuCam)> PossessedMenuCam;               // 0x0BA8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_BP_MainMenu_PC(int32 EntryPoint);
	void Possess_Menu_Cam(class AMenuCamPawn_C* NewParam);
	void ReceiveBeginPlay();
	void Possess_A_Menu_Cam();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MainMenu_PC_C">();
	}
	static class ABP_MainMenu_PC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MainMenu_PC_C>();
	}
};
static_assert(alignof(ABP_MainMenu_PC_C) == 0x000010, "Wrong alignment on ABP_MainMenu_PC_C");
static_assert(sizeof(ABP_MainMenu_PC_C) == 0x000BC0, "Wrong size on ABP_MainMenu_PC_C");
static_assert(offsetof(ABP_MainMenu_PC_C, UberGraphFrame) == 0x000BA0, "Member 'ABP_MainMenu_PC_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_MainMenu_PC_C, PossessedMenuCam) == 0x000BA8, "Member 'ABP_MainMenu_PC_C::PossessedMenuCam' has a wrong offset!");

}

