#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SquadGameInstance

#include "Basic.hpp"

#include "ModdingRuntime_structs.hpp"
#include "UIZOrderStruct_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"


namespace SDK::Params
{

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.ExecuteUbergraph_BP_SquadGameInstance
// 0x02C8 (0x02C8 - 0x0000)
struct BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	struct FVector                                CallFunc_RebaseZeroOriginOntoLocal_ReturnValue;    // 0x0014(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASQJoinBeaconClient*                    K2Node_CustomEvent_NewJoinBeaconClient;            // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x0028(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	struct FVector                                K2Node_CustomEvent_OriginLocation;                 // 0x0048(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuScreen_C*                      CallFunc_GetMainMenuRef_REF_MainMenu;              // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Password;                       // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UBP_ServerPassword_C*                   K2Node_CustomEvent_Sender;                         // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveDataUIWrapper_C*                   CallFunc_SpawnObject_ReturnValue;                  // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMainMenuScreen_C*                      CallFunc_GetMainMenuRef_REF_MainMenu_1;            // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMainMenuScreen_C*                      CallFunc_GetMainMenuRef_REF_MainMenu_2;            // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASQJoinBeaconClient*                    CallFunc_QueueForServer_ReturnValue;               // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanQueueForServer_ReturnValue;            // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuScreen_C*                      CallFunc_GetMainMenuRef_REF_MainMenu_3;            // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBlueprintSessionResult                K2Node_CustomEvent_SessionResult;                  // 0x00A8(0x0108)(ConstParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQSessionInfo*                         CallFunc_SpawnObject_ReturnValue_1;                // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetSession_ReturnValue;                   // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C1[0x7];                                      // 0x01C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuScreen_C*                      CallFunc_GetMainMenuRef_REF_MainMenu_4;            // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E2[0x6];                                      // 0x01E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x01E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F2[0x2];                                      // 0x01F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& Password, class UBP_ServerPassword_C* Sender)> K2Node_CreateDelegate_OutputDelegate_2; // 0x01F4(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0204(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0214(0x0010)(ZeroConstructor, NoDestructor)
	struct FUIZOrderStruct                        CallFunc_GetDataTableRowFromName_OutRow;           // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_229[0x3];                                      // 0x0229(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x022C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_23C[0x4];                                      // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USQGameInstance*                        CallFunc_GetSquadGameInstance_ReturnValue;         // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Check_Mods_In_Sync;                       // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0249(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsSameServer_ReturnValue;                 // 0x024A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_VerifyPassword_ReturnValue;               // 0x024B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_24C[0x4];                                      // 0x024C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ServerPassword_C*                   CallFunc_Create_ReturnValue;                       // 0x0258(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ModdedServerWarning_C*              CallFunc_Create_ReturnValue_1;                     // 0x0260(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASQPlayerController*                    K2Node_DynamicCast_AsSQPlayer_Controller;          // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ShouldSkipPassword_ReturnValue;           // 0x0279(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_27A[0x2];                                      // 0x027A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class ASQJoinBeaconClient* NewJoinBeaconClient)> K2Node_CreateDelegate_OutputDelegate_6; // 0x027C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x028C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x028D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_28E[0x2];                                      // 0x028E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class ASQJoinBeaconClient* NewJoinBeaconClient)> K2Node_CreateDelegate_OutputDelegate_7; // 0x0290(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const struct FBlueprintSessionResult& SessionResult)> K2Node_CreateDelegate_OutputDelegate_8; // 0x02A0(0x0010)(ZeroConstructor, NoDestructor)
	struct FUIZOrderStruct                        CallFunc_GetDataTableRowFromName_OutRow_1;         // 0x02B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_1;    // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B5[0x3];                                      // 0x02B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FVector& OriginLocation)> K2Node_CreateDelegate_OutputDelegate_9;    // 0x02B8(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance");
static_assert(sizeof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance) == 0x0002C8, "Wrong size on BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, EntryPoint) == 0x000000, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_RebaseZeroOriginOntoLocal_ReturnValue) == 0x000014, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_RebaseZeroOriginOntoLocal_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CustomEvent_NewJoinBeaconClient) == 0x000020, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CustomEvent_NewJoinBeaconClient' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_Conv_VectorToLinearColor_ReturnValue) == 0x000028, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_Conv_VectorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CustomEvent_OriginLocation) == 0x000048, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CustomEvent_OriginLocation' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetMainMenuRef_REF_MainMenu) == 0x000058, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetMainMenuRef_REF_MainMenu' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CustomEvent_Password) == 0x000060, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CustomEvent_Password' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CustomEvent_Sender) == 0x000070, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CustomEvent_Sender' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_SpawnObject_ReturnValue) == 0x000078, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetMainMenuRef_REF_MainMenu_1) == 0x000080, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetMainMenuRef_REF_MainMenu_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetMainMenuRef_REF_MainMenu_2) == 0x000088, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetMainMenuRef_REF_MainMenu_2' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_QueueForServer_ReturnValue) == 0x000090, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_QueueForServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_CanQueueForServer_ReturnValue) == 0x000098, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_CanQueueForServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetMainMenuRef_REF_MainMenu_3) == 0x0000A0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetMainMenuRef_REF_MainMenu_3' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CustomEvent_SessionResult) == 0x0000A8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CustomEvent_SessionResult' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue) == 0x0001B0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_SpawnObject_ReturnValue_1) == 0x0001B8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_SpawnObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_SetSession_ReturnValue) == 0x0001C0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_SetSession_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetMainMenuRef_REF_MainMenu_4) == 0x0001C8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetMainMenuRef_REF_MainMenu_4' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x0001D0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x0001D8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue_1) == 0x0001E0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue_2) == 0x0001E1, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetGameInstanceSubsystem_ReturnValue_2) == 0x0001E8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetGameInstanceSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue_3) == 0x0001F0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue_4) == 0x0001F1, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001F4, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_3) == 0x000204, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_4) == 0x000214, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetDataTableRowFromName_OutRow) == 0x000224, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x000228, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_5) == 0x00022C, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetSquadGameInstance_ReturnValue) == 0x000240, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetSquadGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_Check_Mods_In_Sync) == 0x000248, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_Check_Mods_In_Sync' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsValid_ReturnValue_5) == 0x000249, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_IsSameServer_ReturnValue) == 0x00024A, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_IsSameServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_VerifyPassword_ReturnValue) == 0x00024B, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_VerifyPassword_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetPlayerController_ReturnValue) == 0x000250, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_Create_ReturnValue) == 0x000258, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_Create_ReturnValue_1) == 0x000260, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetPlayerController_ReturnValue_1) == 0x000268, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_DynamicCast_AsSQPlayer_Controller) == 0x000270, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_DynamicCast_AsSQPlayer_Controller' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_DynamicCast_bSuccess) == 0x000278, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_ShouldSkipPassword_ReturnValue) == 0x000279, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_ShouldSkipPassword_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_6) == 0x00027C, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_Not_PreBool_ReturnValue) == 0x00028C, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_BooleanAND_ReturnValue) == 0x00028D, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_7) == 0x000290, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_8) == 0x0002A0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetDataTableRowFromName_OutRow_1) == 0x0002B0, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetDataTableRowFromName_OutRow_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, CallFunc_GetDataTableRowFromName_ReturnValue_1) == 0x0002B4, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::CallFunc_GetDataTableRowFromName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance, K2Node_CreateDelegate_OutputDelegate_9) == 0x0002B8, "Member 'BP_SquadGameInstance_C_ExecuteUbergraph_BP_SquadGameInstance::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.OnSessionFound
// 0x0108 (0x0108 - 0x0000)
struct BP_SquadGameInstance_C_OnSessionFound final
{
public:
	struct FBlueprintSessionResult                SessionResult;                                     // 0x0000(0x0108)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(BP_SquadGameInstance_C_OnSessionFound) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_OnSessionFound");
static_assert(sizeof(BP_SquadGameInstance_C_OnSessionFound) == 0x000108, "Wrong size on BP_SquadGameInstance_C_OnSessionFound");
static_assert(offsetof(BP_SquadGameInstance_C_OnSessionFound, SessionResult) == 0x000000, "Member 'BP_SquadGameInstance_C_OnSessionFound::SessionResult' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.passwordEnteredForced
// 0x0018 (0x0018 - 0x0000)
struct BP_SquadGameInstance_C_passwordEnteredForced final
{
public:
	class FString                                 Password;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UBP_ServerPassword_C*                   Sender;                                            // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SquadGameInstance_C_passwordEnteredForced) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_passwordEnteredForced");
static_assert(sizeof(BP_SquadGameInstance_C_passwordEnteredForced) == 0x000018, "Wrong size on BP_SquadGameInstance_C_passwordEnteredForced");
static_assert(offsetof(BP_SquadGameInstance_C_passwordEnteredForced, Password) == 0x000000, "Member 'BP_SquadGameInstance_C_passwordEnteredForced::Password' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_passwordEnteredForced, Sender) == 0x000010, "Member 'BP_SquadGameInstance_C_passwordEnteredForced::Sender' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.HandleOnQueueForServer
// 0x0008 (0x0008 - 0x0000)
struct BP_SquadGameInstance_C_HandleOnQueueForServer final
{
public:
	class ASQJoinBeaconClient*                    NewJoinBeaconClient;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SquadGameInstance_C_HandleOnQueueForServer) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_HandleOnQueueForServer");
static_assert(sizeof(BP_SquadGameInstance_C_HandleOnQueueForServer) == 0x000008, "Wrong size on BP_SquadGameInstance_C_HandleOnQueueForServer");
static_assert(offsetof(BP_SquadGameInstance_C_HandleOnQueueForServer, NewJoinBeaconClient) == 0x000000, "Member 'BP_SquadGameInstance_C_HandleOnQueueForServer::NewJoinBeaconClient' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.On Origin Rebase
// 0x000C (0x000C - 0x0000)
struct BP_SquadGameInstance_C_On_Origin_Rebase final
{
public:
	struct FVector                                OriginLocation;                                    // 0x0000(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SquadGameInstance_C_On_Origin_Rebase) == 0x000004, "Wrong alignment on BP_SquadGameInstance_C_On_Origin_Rebase");
static_assert(sizeof(BP_SquadGameInstance_C_On_Origin_Rebase) == 0x00000C, "Wrong size on BP_SquadGameInstance_C_On_Origin_Rebase");
static_assert(offsetof(BP_SquadGameInstance_C_On_Origin_Rebase, OriginLocation) == 0x000000, "Member 'BP_SquadGameInstance_C_On_Origin_Rebase::OriginLocation' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.Set UI Data
// 0x0008 (0x0008 - 0x0000)
struct BP_SquadGameInstance_C_Set_UI_Data final
{
public:
	class USaveData_UI_C*                         UISaveData;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SquadGameInstance_C_Set_UI_Data) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_Set_UI_Data");
static_assert(sizeof(BP_SquadGameInstance_C_Set_UI_Data) == 0x000008, "Wrong size on BP_SquadGameInstance_C_Set_UI_Data");
static_assert(offsetof(BP_SquadGameInstance_C_Set_UI_Data, UISaveData) == 0x000000, "Member 'BP_SquadGameInstance_C_Set_UI_Data::UISaveData' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.Get UI Data
// 0x0020 (0x0020 - 0x0000)
struct BP_SquadGameInstance_C_Get_UI_Data final
{
public:
	class USaveData_UI_C*                         AsSave_Data_UI;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveGame*                              CallFunc_GetSavedGame_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveData_UI_C*                         K2Node_DynamicCast_AsSave_Data_UI;                 // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SquadGameInstance_C_Get_UI_Data) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_Get_UI_Data");
static_assert(sizeof(BP_SquadGameInstance_C_Get_UI_Data) == 0x000020, "Wrong size on BP_SquadGameInstance_C_Get_UI_Data");
static_assert(offsetof(BP_SquadGameInstance_C_Get_UI_Data, AsSave_Data_UI) == 0x000000, "Member 'BP_SquadGameInstance_C_Get_UI_Data::AsSave_Data_UI' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Get_UI_Data, CallFunc_GetSavedGame_ReturnValue) == 0x000008, "Member 'BP_SquadGameInstance_C_Get_UI_Data::CallFunc_GetSavedGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Get_UI_Data, K2Node_DynamicCast_AsSave_Data_UI) == 0x000010, "Member 'BP_SquadGameInstance_C_Get_UI_Data::K2Node_DynamicCast_AsSave_Data_UI' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Get_UI_Data, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_SquadGameInstance_C_Get_UI_Data::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.GetMainMenuRef
// 0x0038 (0x0038 - 0x0000)
struct BP_SquadGameInstance_C_GetMainMenuRef final
{
public:
	class UMainMenuScreen_C*                      REF_MainMenu;                                      // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_HUD_C*                              K2Node_DynamicCast_AsBP_HUD;                       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_HUDMenu_C*                          K2Node_DynamicCast_AsBP_HUDMenu;                   // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SquadGameInstance_C_GetMainMenuRef) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_GetMainMenuRef");
static_assert(sizeof(BP_SquadGameInstance_C_GetMainMenuRef) == 0x000038, "Wrong size on BP_SquadGameInstance_C_GetMainMenuRef");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, REF_MainMenu) == 0x000000, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::REF_MainMenu' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, CallFunc_GetPlayerController_ReturnValue) == 0x000008, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, CallFunc_GetHUD_ReturnValue) == 0x000010, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, K2Node_DynamicCast_AsBP_HUD) == 0x000018, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::K2Node_DynamicCast_AsBP_HUD' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, K2Node_DynamicCast_AsBP_HUDMenu) == 0x000028, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::K2Node_DynamicCast_AsBP_HUDMenu' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, K2Node_DynamicCast_bSuccess_1) == 0x000030, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, CallFunc_IsValid_ReturnValue) == 0x000031, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_GetMainMenuRef, CallFunc_IsValid_ReturnValue_1) == 0x000032, "Member 'BP_SquadGameInstance_C_GetMainMenuRef::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");

// Function BP_SquadGameInstance.BP_SquadGameInstance_C.Check Mods
// 0x0050 (0x0050 - 0x0000)
struct BP_SquadGameInstance_C_Check_Mods final
{
public:
	class USQSessionInfo*                         SessionInfo_0;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          In_Sync;                                           // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSQModLoadProgress>             CallFunc_CheckMissingMods_ReturnValue;             // 0x0010(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_ModDownloadWindow_C*                 CallFunc_Create_ReturnValue;                       // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0040(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(BP_SquadGameInstance_C_Check_Mods) == 0x000008, "Wrong alignment on BP_SquadGameInstance_C_Check_Mods");
static_assert(sizeof(BP_SquadGameInstance_C_Check_Mods) == 0x000050, "Wrong size on BP_SquadGameInstance_C_Check_Mods");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, SessionInfo_0) == 0x000000, "Member 'BP_SquadGameInstance_C_Check_Mods::SessionInfo_0' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, In_Sync) == 0x000008, "Member 'BP_SquadGameInstance_C_Check_Mods::In_Sync' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_CheckMissingMods_ReturnValue) == 0x000010, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_CheckMissingMods_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_Array_Length_ReturnValue) == 0x000024, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000028, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_GetPlayerController_ReturnValue) == 0x000030, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, CallFunc_Create_ReturnValue) == 0x000038, "Member 'BP_SquadGameInstance_C_Check_Mods::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SquadGameInstance_C_Check_Mods, K2Node_CreateDelegate_OutputDelegate) == 0x000040, "Member 'BP_SquadGameInstance_C_Check_Mods::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

}

