#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CaptureZoneModifier

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_CaptureZoneModifier.BPI_CaptureZoneModifier_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_CaptureZoneModifier_C final
{
public:
	void Additional_Can_Capture(bool* Can_Capture);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_CaptureZoneModifier_C">();
	}
	static class IBPI_CaptureZoneModifier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_CaptureZoneModifier_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_CaptureZoneModifier_C) == 0x000001, "Wrong alignment on IBPI_CaptureZoneModifier_C");
static_assert(sizeof(IBPI_CaptureZoneModifier_C) == 0x000001, "Wrong size on IBPI_CaptureZoneModifier_C");

}

