#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_BoundaryInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_BoundaryInterface.BPI_BoundaryInterface_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_BoundaryInterface_C final
{
public:
	void On_Out_of_Bounds();
	void On_Entered_Bounds();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_BoundaryInterface_C">();
	}
	static class IBPI_BoundaryInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_BoundaryInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_BoundaryInterface_C) == 0x000001, "Wrong alignment on IBPI_BoundaryInterface_C");
static_assert(sizeof(IBPI_BoundaryInterface_C) == 0x000001, "Wrong size on IBPI_BoundaryInterface_C");

}

