#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_VoteScreen

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_VoteScreen.BPI_VoteScreen_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_VoteScreen_C final
{
public:
	void OnVoteStarted(class USQVoteSessionClient* VoteSession, bool VotePossible);
	void OnVoteUpdated(class USQVoteSessionClient* VoteSession, int32 PlayerCurrentVoteCount);
	void OnVoteEnded(class USQVoteSessionClient* VoteSession, const struct FSQChoice& Winner);
	void SetVoteScreenActive(bool Activated);
	void OnVoteUpdatedByID(class FName ChoiceId);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_VoteScreen_C">();
	}
	static class IBPI_VoteScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_VoteScreen_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_VoteScreen_C) == 0x000001, "Wrong alignment on IBPI_VoteScreen_C");
static_assert(sizeof(IBPI_VoteScreen_C) == 0x000001, "Wrong size on IBPI_VoteScreen_C");

}

