#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Menus

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Menus.BPI_Menus_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Menus_C final
{
public:
	void Open_UI_Element(class USQCoreStateMapComponent* Map_Component, bool* Success);
	void Close_UI_Element(bool* Success);
	void Key_Action();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Menus_C">();
	}
	static class IBPI_Menus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Menus_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Menus_C) == 0x000001, "Wrong alignment on IBPI_Menus_C");
static_assert(sizeof(IBPI_Menus_C) == 0x000001, "Wrong size on IBPI_Menus_C");

}

