#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Scoreboard

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Scoreboard.BPI_Scoreboard_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Scoreboard_C final
{
public:
	void Play_Fade_Animation();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Scoreboard_C">();
	}
	static class IBPI_Scoreboard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Scoreboard_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Scoreboard_C) == 0x000001, "Wrong alignment on IBPI_Scoreboard_C");
static_assert(sizeof(IBPI_Scoreboard_C) == 0x000001, "Wrong size on IBPI_Scoreboard_C");

}

