#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_BaseHud

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_BaseHud.BPI_BaseHUD_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_BaseHUD_C final
{
public:
	void Get_Destruction_Event_Widget(class UW_DestructionObjectiveEvent_C** Destruction_Event_Widget);
	void Get_Capture_Event_Widget(class UW_FlagCapturedEvent_C** Capture_Event_Widget);
	void Get_Seeding_Phase_Widget(class UUMG_SeedingPhaseStatusText_C** SeedingPhaseWidget);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_BaseHUD_C">();
	}
	static class IBPI_BaseHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_BaseHUD_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_BaseHUD_C) == 0x000001, "Wrong alignment on IBPI_BaseHUD_C");
static_assert(sizeof(IBPI_BaseHUD_C) == 0x000001, "Wrong size on IBPI_BaseHUD_C");

}

