#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_Helicopter

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_Helicopter.BPI_Helicopter_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_Helicopter_C final
{
public:
	void Is_Using_Landing_Camera(bool* Using_Landing_Camera);
	void Get_UI_Tint(struct FLinearColor* Color);
	void Set_Landing_Camera(bool Active);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_Helicopter_C">();
	}
	static class IBPI_Helicopter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_Helicopter_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_Helicopter_C) == 0x000001, "Wrong alignment on IBPI_Helicopter_C");
static_assert(sizeof(IBPI_Helicopter_C) == 0x000001, "Wrong size on IBPI_Helicopter_C");

}

