#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_UI_Events

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass I_UI_Events.I_UI_Events_C
// 0x0000 (0x0000 - 0x0000)
class II_UI_Events_C final
{
public:
	void Team_Selected(int32 Team_ID);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"I_UI_Events_C">();
	}
	static class II_UI_Events_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<II_UI_Events_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(II_UI_Events_C) == 0x000001, "Wrong alignment on II_UI_Events_C");
static_assert(sizeof(II_UI_Events_C) == 0x000001, "Wrong size on II_UI_Events_C");

}

