#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IDeployableEvents

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IDeployableEvents.IDeployableEvents_C
// 0x0000 (0x0000 - 0x0000)
class IIDeployableEvents_C final
{
public:
	void OnServerValidatedItemPlacement(class ASQDeployableItem* Deployable);
	void OnClientInvalidatedItemPlacement();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IDeployableEvents_C">();
	}
	static class IIDeployableEvents_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IIDeployableEvents_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IIDeployableEvents_C) == 0x000001, "Wrong alignment on IIDeployableEvents_C");
static_assert(sizeof(IIDeployableEvents_C) == 0x000001, "Wrong size on IIDeployableEvents_C");

}

