#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IWidget_Interactable

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IWidget_Interactable.IWidget_Interactable_C
// 0x0000 (0x0000 - 0x0000)
class IIWidget_Interactable_C final
{
public:
	void Set_Interactable_Actor(class AActor* Actor);
	void Set_Interact_Data(const struct FSQUsableWidgetData& Interact_Data, class AActor* Actor);
	void Clear_Interactable();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IWidget_Interactable_C">();
	}
	static class IIWidget_Interactable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IIWidget_Interactable_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IIWidget_Interactable_C) == 0x000001, "Wrong alignment on IIWidget_Interactable_C");
static_assert(sizeof(IIWidget_Interactable_C) == 0x000001, "Wrong size on IIWidget_Interactable_C");

}

