#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Setting_Button

#include "Basic.hpp"

#include "Setting_Button_classes.hpp"
#include "Setting_Button_parameters.hpp"


namespace SDK
{

// Function Setting_Button.Setting_Button_C.ExecuteUbergraph_Setting_Button
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetting_Button_C::ExecuteUbergraph_Setting_Button(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "ExecuteUbergraph_Setting_Button");

	Params::Setting_Button_C_ExecuteUbergraph_Setting_Button Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Setting_Button.Setting_Button_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USetting_Button_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USetting_Button_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "PreConstruct");

	Params::Setting_Button_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Setting_Button.Setting_Button_C.BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USetting_Button_C::BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "BndEvt__Button_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USetting_Button_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Tick");

	Params::Setting_Button_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Setting_Button.Setting_Button_C.SetSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bSelected_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USetting_Button_C::SetSelected(bool bSelected_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "SetSelected");

	Params::Setting_Button_C_SetSelected Parms{};

	Parms.bSelected_0 = bSelected_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Setting_Button.Setting_Button_C.UpdateColors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USetting_Button_C::UpdateColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "UpdateColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.SetText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void USetting_Button_C::SetText(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "SetText");

	Params::Setting_Button_C_SetText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Setting_Button.Setting_Button_C.Bind_LineColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor USetting_Button_C::Bind_LineColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Bind_LineColor");

	Params::Setting_Button_C_Bind_LineColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Setting_Button.Setting_Button_C.Bind_TextColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateColor                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateColor USetting_Button_C::Bind_TextColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Bind_TextColor");

	Params::Setting_Button_C_Bind_TextColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Setting_Button.Setting_Button_C.Update Button
// (Public, BlueprintCallable, BlueprintEvent)

void USetting_Button_C::Update_Button()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Update Button");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.Setup Button
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void USetting_Button_C::Setup_Button()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Setup Button");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.Refresh Line
// (Public, BlueprintCallable, BlueprintEvent)

void USetting_Button_C::Refresh_Line()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "Refresh Line");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Setting_Button.Setting_Button_C.OnKeyDown
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FKeyEvent&                 InKeyEvent                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply USetting_Button_C::OnKeyDown(const struct FGeometry& MyGeometry, const struct FKeyEvent& InKeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Setting_Button_C", "OnKeyDown");

	Params::Setting_Button_C_OnKeyDown Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InKeyEvent = std::move(InKeyEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

