#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SQOnlineServices

#include "Basic.hpp"


namespace SDK
{

// Enum SQOnlineServices.ESQFriendInvitePolicy
// NumValues: 0x0005
enum class ESQFriendInvitePolicy : uint8
{
	Public                                   = 0,
	FriendsOfFriends                         = 1,
	Private                                  = 2,
	InvalidOrMax                             = 3,
	ESQFriendInvitePolicy_MAX                = 4,
};

// Enum SQOnlineServices.ESQInviteStatus
// NumValues: 0x0007
enum class ESQInviteStatus : uint8
{
	Unknown                                  = 0,
	Accepted                                 = 1,
	PendingInbound                           = 2,
	PendingOutbound                          = 3,
	Blocked                                  = 4,
	Suggested                                = 5,
	ESQInviteStatus_MAX                      = 6,
};

}

