#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SQOnlineServices

#include "Basic.hpp"

#include "SQOnlineServices_classes.hpp"
#include "SQOnlineServices_parameters.hpp"


namespace SDK
{

// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetPlatform
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesOnlineUser::GetPlatform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetPlatform");

	Params::SQOnlineServicesOnlineUser_GetPlatform Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetUserAvatar
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UTexture*                         DefaultTexture                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USQOnlineServicesOnlineUser::GetUserAvatar(class UTexture* DefaultTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetUserAvatar");

	Params::SQOnlineServicesOnlineUser_GetUserAvatar Parms{};

	Parms.DefaultTexture = DefaultTexture;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.IsReady
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesOnlineUser::IsReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "IsReady");

	Params::SQOnlineServicesOnlineUser_IsReady Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetRealName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesOnlineUser::GetRealName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetRealName");

	Params::SQOnlineServicesOnlineUser_GetRealName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetRelatedIds
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// TArray<class FString>                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class FString> USQOnlineServicesOnlineUser::GetRelatedIds() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetRelatedIds");

	Params::SQOnlineServicesOnlineUser_GetRelatedIds Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetSteamID
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesOnlineUser::GetSteamID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetSteamID");

	Params::SQOnlineServicesOnlineUser_GetSteamID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetUniqueID
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FUniqueNetIdRepl                 ReturnValue                                            (Parm, OutParm, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FUniqueNetIdRepl USQOnlineServicesOnlineUser::GetUniqueID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetUniqueID");

	Params::SQOnlineServicesOnlineUser_GetUniqueID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetUniqueIDString
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesOnlineUser::GetUniqueIDString() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetUniqueIDString");

	Params::SQOnlineServicesOnlineUser_GetUniqueIDString Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesOnlineUser.GetUserName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesOnlineUser::GetUserName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesOnlineUser", "GetUserName");

	Params::SQOnlineServicesOnlineUser_GetUserName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriends.FindFriendSession
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class USQOnlineServicesFriendUser*User                                                   (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USQOnlineServicesFriends::FindFriendSession(const class USQOnlineServicesFriendUser* User)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriends", "FindFriendSession");

	Params::SQOnlineServicesFriends_FindFriendSession Parms{};

	Parms.User = User;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesFriends.GetCachedFriendsList
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TArray<class USQOnlineServicesFriendUser*>ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class USQOnlineServicesFriendUser*> USQOnlineServicesFriends::GetCachedFriendsList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriends", "GetCachedFriendsList");

	Params::SQOnlineServicesFriends_GetCachedFriendsList Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriends.IsFriend
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUniqueNetIdRepl&          FriendId                                               (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriends::IsFriend(const struct FUniqueNetIdRepl& FriendId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriends", "IsFriend");

	Params::SQOnlineServicesFriends_IsFriend Parms{};

	Parms.FriendId = std::move(FriendId);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriends.RequestUpdateFriendsList
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriends::RequestUpdateFriendsList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriends", "RequestUpdateFriendsList");

	Params::SQOnlineServicesFriends_RequestUpdateFriendsList Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.IsFriendInSession
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FBlueprintSessionResult&   Session                                                (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::IsFriendInSession(const struct FBlueprintSessionResult& Session)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "IsFriendInSession");

	Params::SQOnlineServicesFriendUser_IsFriendInSession Parms{};

	Parms.Session = std::move(Session);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.UpdateCachedPresence
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::UpdateCachedPresence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "UpdateCachedPresence");

	Params::SQOnlineServicesFriendUser_UpdateCachedPresence Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetInviteStatus
// (Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// ESQInviteStatus                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

ESQInviteStatus USQOnlineServicesFriendUser::GetInviteStatus() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetInviteStatus");

	Params::SQOnlineServicesFriendUser_GetInviteStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetIsJoinable
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::GetIsJoinable() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetIsJoinable");

	Params::SQOnlineServicesFriendUser_GetIsJoinable Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetIsOnline
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::GetIsOnline() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetIsOnline");

	Params::SQOnlineServicesFriendUser_GetIsOnline Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetIsPlaying
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::GetIsPlaying() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetIsPlaying");

	Params::SQOnlineServicesFriendUser_GetIsPlaying Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetIsPlayingThisGame
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesFriendUser::GetIsPlayingThisGame() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetIsPlayingThisGame");

	Params::SQOnlineServicesFriendUser_GetIsPlayingThisGame Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetPresenceFactionID
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetPresenceFactionID() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetPresenceFactionID");

	Params::SQOnlineServicesFriendUser_GetPresenceFactionID Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetPresenceFactionName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetPresenceFactionName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetPresenceFactionName");

	Params::SQOnlineServicesFriendUser_GetPresenceFactionName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetPresenceMapName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetPresenceMapName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetPresenceMapName");

	Params::SQOnlineServicesFriendUser_GetPresenceMapName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetPresencePlayerCount
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetPresencePlayerCount() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetPresencePlayerCount");

	Params::SQOnlineServicesFriendUser_GetPresencePlayerCount Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetPresenceServerName
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetPresenceServerName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetPresenceServerName");

	Params::SQOnlineServicesFriendUser_GetPresenceServerName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesFriendUser.GetStatus
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesFriendUser::GetStatus() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesFriendUser", "GetStatus");

	Params::SQOnlineServicesFriendUser_GetStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesParty.CreateParty
// (Final, Native, Public, BlueprintCallable)

void USQOnlineServicesParty::CreateParty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "CreateParty");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesParty.GetPartyLeader
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class USQOnlineServicesPartyUser*       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USQOnlineServicesPartyUser* USQOnlineServicesParty::GetPartyLeader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "GetPartyLeader");

	Params::SQOnlineServicesParty_GetPartyLeader Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesParty.GetPartyMembers
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TArray<class USQOnlineServicesPartyUser*>ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)

TArray<class USQOnlineServicesPartyUser*> USQOnlineServicesParty::GetPartyMembers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "GetPartyMembers");

	Params::SQOnlineServicesParty_GetPartyMembers Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesParty.IsPartyLeader
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUniqueNetIdRepl&          PartyMember                                            (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesParty::IsPartyLeader(const struct FUniqueNetIdRepl& PartyMember)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "IsPartyLeader");

	Params::SQOnlineServicesParty_IsPartyLeader Parms{};

	Parms.PartyMember = std::move(PartyMember);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesParty.IsPartyUserLeader
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class USQOnlineServicesPartyUser* PartyMember                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool USQOnlineServicesParty::IsPartyUserLeader(const class USQOnlineServicesPartyUser* PartyMember)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "IsPartyUserLeader");

	Params::SQOnlineServicesParty_IsPartyUserLeader Parms{};

	Parms.PartyMember = PartyMember;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesParty.KickPlayer
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUniqueNetIdRepl&          Player                                                 (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USQOnlineServicesParty::KickPlayer(const struct FUniqueNetIdRepl& Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "KickPlayer");

	Params::SQOnlineServicesParty_KickPlayer Parms{};

	Parms.Player = std::move(Player);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesParty.LeaveParty
// (Final, Native, Public, BlueprintCallable)

void USQOnlineServicesParty::LeaveParty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "LeaveParty");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesParty.PromoteLeader
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const struct FUniqueNetIdRepl&          Player                                                 (ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USQOnlineServicesParty::PromoteLeader(const struct FUniqueNetIdRepl& Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesParty", "PromoteLeader");

	Params::SQOnlineServicesParty_PromoteLeader Parms{};

	Parms.Player = std::move(Player);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesRecentUser.GetLastSeenString
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString USQOnlineServicesRecentUser::GetLastSeenString()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesRecentUser", "GetLastSeenString");

	Params::SQOnlineServicesRecentUser_GetLastSeenString Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function SQOnlineServices.SQOnlineServicesSubsystem.SetPlayerPresence
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ServerName                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Faction                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    FactionID                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Map                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Players                                                (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bDisplayDetails                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void USQOnlineServicesSubsystem::SetPlayerPresence(const class FString& ServerName, const class FString& Faction, const class FString& FactionID, const class FString& Map, const class FString& Players, bool bDisplayDetails)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesSubsystem", "SetPlayerPresence");

	Params::SQOnlineServicesSubsystem_SetPlayerPresence Parms{};

	Parms.ServerName = std::move(ServerName);
	Parms.Faction = std::move(Faction);
	Parms.FactionID = std::move(FactionID);
	Parms.Map = std::move(Map);
	Parms.Players = std::move(Players);
	Parms.bDisplayDetails = bDisplayDetails;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesSubsystem.SetStatusDefault
// (Final, Native, Public, BlueprintCallable)

void USQOnlineServicesSubsystem::SetStatusDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesSubsystem", "SetStatusDefault");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function SQOnlineServices.SQOnlineServicesSubsystem.GetLocalUser
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class USQOnlineServicesLocalUser*       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USQOnlineServicesLocalUser* USQOnlineServicesSubsystem::GetLocalUser() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SQOnlineServicesSubsystem", "GetLocalUser");

	Params::SQOnlineServicesSubsystem_GetLocalUser Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

