#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Friend

#include "Basic.hpp"

#include "W_Friend_classes.hpp"
#include "W_Friend_parameters.hpp"


namespace SDK
{

// Function W_Friend.W_Friend_C.ExecuteUbergraph_W_Friend
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Friend_C::ExecuteUbergraph_W_Friend(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "ExecuteUbergraph_W_Friend");

	Params::W_Friend_C_ExecuteUbergraph_W_Friend Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Friend.W_Friend_C.AsyncLoadFlag
// (BlueprintCallable, BlueprintEvent)

void UW_Friend_C::AsyncLoadFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "AsyncLoadFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Friend.W_Friend_C.BndEvt__W_Friend_Button_Main_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Friend_C::BndEvt__W_Friend_Button_Main_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "BndEvt__W_Friend_Button_Main_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Friend.W_Friend_C.BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMainMenu_Button_C*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Friend_C::BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");

	Params::W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Friend.W_Friend_C.BndEvt__Button_64_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_Friend_C::BndEvt__Button_64_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "BndEvt__Button_64_K2Node_ComponentBoundEvent_18_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Friend.W_Friend_C.Init Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Friend_C::Init_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "Init Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Friend.W_Friend_C.OnAvatarGetComplete
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UTexture*                         ResultTexture                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Friend_C::OnAvatarGetComplete(bool bWasSuccessful, class UTexture* ResultTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "OnAvatarGetComplete");

	Params::W_Friend_C_OnAvatarGetComplete Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.ResultTexture = ResultTexture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Friend.W_Friend_C.InitPresence
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UW_Friend_C::InitPresence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "InitPresence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_Friend.W_Friend_C.Get_ButtonJoin_bIsEnabled_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UW_Friend_C::Get_ButtonJoin_bIsEnabled_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Friend_C", "Get_ButtonJoin_bIsEnabled_0");

	Params::W_Friend_C_Get_ButtonJoin_bIsEnabled_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

