#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FriendsList

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Squad_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_FriendsList.W_FriendsList_C
// 0x0130 (0x03E8 - 0x02B8)
class UW_FriendsList_C final : public USQFriendsBrowserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OpenFriends;                                       // 0x02C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                Border_InGame;                                     // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Offline;                                    // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_Online;                                     // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Button_Hover;                                      // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMainMenu_Button_C*                     Button_InGameTab;                                  // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMainMenu_Button_C*                     Button_OfflineTab;                                 // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMainMenu_Button_C*                     Button_OnlineTab_1;                                // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         HorizontalBox_FriendCount;                         // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_63;                                          // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_Friends;                                 // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_FriendsList;                               // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_230;                                     // 0x0320(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_OfflineFriends;                        // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_OnlineFriends;                         // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_SquadFriends;                          // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         PresenceRefreshTime;                               // 0x0340(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_344[0x4];                                      // 0x0344(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class USQSessionInfo* FriendSession)> OnRequestJoinFriend;         // 0x0348(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<class USQOnlineServicesFriendUser*>    CurrentCachedFriendsList;                          // 0x0358(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class FString, class UW_Friend_C*>       FriendWidgetMap_0;                                 // 0x0368(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FTimerHandle                           PresenceQueryTimerHandle;                          // 0x03B8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bLoaded;                                           // 0x03C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C1[0x7];                                      // 0x03C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQSessionInfo*                         SessionInfo;                                       // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMainMenuScreen_C*                      REF_MainMenu;                                      // 0x03D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ServerPassword_C*                   ServerPasswordWidget;                              // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_ModdedServerWarning_C*              ModdedServerWarning;                               // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_FriendsList(int32 EntryPoint);
	void ResetScroll();
	void BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void PreConstruct(bool IsDesignTime);
	void BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button);
	void BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button);
	void BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button);
	void OnFriendSessionFound(const struct FBlueprintSessionResult& SessionResult);
	void HandleRequestJoin(class USQOnlineServicesFriendUser* FriendUser);
	void OnInitialized();
	void ShowCachedFriends();
	void BP_OnUpdateFriendPresence(const class USQOnlineServicesFriendUser* FriendUser);
	void BP_OnUpdateFriendsListComplete(const TArray<class USQOnlineServicesFriendUser*>& Results, bool bWasSuccessful);
	void AddFriendToList(class UVerticalBox* List, class UWidget* Content);
	void ClearAllFriends();
	class FText GetText_0();
	ESlateVisibility GetVisibility_0();
	void HandleFriendPresenceChanged(class UW_Friend_C* FriendWidget);
	void PopulateFriendsListByIndividual(class USQOnlineServicesFriendUser* OnlineUser);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_FriendsList_C">();
	}
	static class UW_FriendsList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_FriendsList_C>();
	}
};
static_assert(alignof(UW_FriendsList_C) == 0x000008, "Wrong alignment on UW_FriendsList_C");
static_assert(sizeof(UW_FriendsList_C) == 0x0003E8, "Wrong size on UW_FriendsList_C");
static_assert(offsetof(UW_FriendsList_C, UberGraphFrame) == 0x0002B8, "Member 'UW_FriendsList_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, OpenFriends) == 0x0002C0, "Member 'UW_FriendsList_C::OpenFriends' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Border_InGame) == 0x0002C8, "Member 'UW_FriendsList_C::Border_InGame' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Border_Offline) == 0x0002D0, "Member 'UW_FriendsList_C::Border_Offline' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Border_Online) == 0x0002D8, "Member 'UW_FriendsList_C::Border_Online' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Button_Hover) == 0x0002E0, "Member 'UW_FriendsList_C::Button_Hover' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Button_InGameTab) == 0x0002E8, "Member 'UW_FriendsList_C::Button_InGameTab' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Button_OfflineTab) == 0x0002F0, "Member 'UW_FriendsList_C::Button_OfflineTab' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Button_OnlineTab_1) == 0x0002F8, "Member 'UW_FriendsList_C::Button_OnlineTab_1' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, HorizontalBox_FriendCount) == 0x000300, "Member 'UW_FriendsList_C::HorizontalBox_FriendCount' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, Image_63) == 0x000308, "Member 'UW_FriendsList_C::Image_63' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, ScrollBox_Friends) == 0x000310, "Member 'UW_FriendsList_C::ScrollBox_Friends' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, SizeBox_FriendsList) == 0x000318, "Member 'UW_FriendsList_C::SizeBox_FriendsList' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, TextBlock_230) == 0x000320, "Member 'UW_FriendsList_C::TextBlock_230' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, VerticalBox_OfflineFriends) == 0x000328, "Member 'UW_FriendsList_C::VerticalBox_OfflineFriends' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, VerticalBox_OnlineFriends) == 0x000330, "Member 'UW_FriendsList_C::VerticalBox_OnlineFriends' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, VerticalBox_SquadFriends) == 0x000338, "Member 'UW_FriendsList_C::VerticalBox_SquadFriends' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, PresenceRefreshTime) == 0x000340, "Member 'UW_FriendsList_C::PresenceRefreshTime' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, OnRequestJoinFriend) == 0x000348, "Member 'UW_FriendsList_C::OnRequestJoinFriend' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, CurrentCachedFriendsList) == 0x000358, "Member 'UW_FriendsList_C::CurrentCachedFriendsList' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, FriendWidgetMap_0) == 0x000368, "Member 'UW_FriendsList_C::FriendWidgetMap_0' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, PresenceQueryTimerHandle) == 0x0003B8, "Member 'UW_FriendsList_C::PresenceQueryTimerHandle' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, bLoaded) == 0x0003C0, "Member 'UW_FriendsList_C::bLoaded' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, SessionInfo) == 0x0003C8, "Member 'UW_FriendsList_C::SessionInfo' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, REF_MainMenu) == 0x0003D0, "Member 'UW_FriendsList_C::REF_MainMenu' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, ServerPasswordWidget) == 0x0003D8, "Member 'UW_FriendsList_C::ServerPasswordWidget' has a wrong offset!");
static_assert(offsetof(UW_FriendsList_C, ModdedServerWarning) == 0x0003E0, "Member 'UW_FriendsList_C::ModdedServerWarning' has a wrong offset!");

}

