#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Friend

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function W_Friend.W_Friend_C.ExecuteUbergraph_W_Friend
// 0x00B8 (0x00B8 - 0x0000)
struct W_Friend_C_ExecuteUbergraph_W_Friend final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPresenceMapName_ReturnValue;           // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPresenceServerName_ReturnValue;        // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StriStri_ReturnValue;          // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0032(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0033(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bSelected;              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     K2Node_ComponentBoundEvent_Button;                 // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue;         // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue_1;       // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue;                  // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue_1;                // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47[0x1];                                       // 0x0047(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPresenceFactionID_ReturnValue;         // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetPresenceMapName_ReturnValue_1;         // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UTexture2D>              CallFunc_ParseFactionFlag_OutFlag;                 // 0x0070(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_ParseFactionFlag_ReturnValue;             // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue_1;          // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEmpty_ReturnValue_1;                    // 0x009A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9B[0x5];                                       // 0x009B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPresenceServerName_ReturnValue_1;      // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_StriStri_ReturnValue_1;        // 0x00B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x00B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_Friend_C_ExecuteUbergraph_W_Friend) == 0x000008, "Wrong alignment on W_Friend_C_ExecuteUbergraph_W_Friend");
static_assert(sizeof(W_Friend_C_ExecuteUbergraph_W_Friend) == 0x0000B8, "Wrong size on W_Friend_C_ExecuteUbergraph_W_Friend");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, EntryPoint) == 0x000000, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000008, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetPresenceMapName_ReturnValue) == 0x000010, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetPresenceMapName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetPresenceServerName_ReturnValue) == 0x000020, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetPresenceServerName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x000030, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_EqualEqual_StriStri_ReturnValue) == 0x000031, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_EqualEqual_StriStri_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_IsEmpty_ReturnValue) == 0x000032, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanOR_ReturnValue) == 0x000033, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, K2Node_ComponentBoundEvent_bSelected) == 0x000034, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::K2Node_ComponentBoundEvent_bSelected' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, K2Node_ComponentBoundEvent_Button) == 0x000038, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanOR_ReturnValue_1) == 0x000040, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetIsPlayingThisGame_ReturnValue) == 0x000041, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetIsPlayingThisGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetIsPlayingThisGame_ReturnValue_1) == 0x000042, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetIsPlayingThisGame_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetIsOnline_ReturnValue) == 0x000043, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetIsOnline_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetIsOnline_ReturnValue_1) == 0x000044, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetIsOnline_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanAND_ReturnValue) == 0x000045, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanAND_ReturnValue_1) == 0x000046, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetPresenceFactionID_ReturnValue) == 0x000048, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetPresenceFactionID_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_Conv_StringToName_ReturnValue) == 0x000058, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetPresenceMapName_ReturnValue_1) == 0x000060, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetPresenceMapName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_ParseFactionFlag_OutFlag) == 0x000070, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_ParseFactionFlag_OutFlag' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_ParseFactionFlag_ReturnValue) == 0x000098, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_ParseFactionFlag_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_EqualEqual_StrStr_ReturnValue_1) == 0x000099, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_EqualEqual_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_IsEmpty_ReturnValue_1) == 0x00009A, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_IsEmpty_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_GetPresenceServerName_ReturnValue_1) == 0x0000A0, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_GetPresenceServerName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanOR_ReturnValue_2) == 0x0000B0, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_EqualEqual_StriStri_ReturnValue_1) == 0x0000B1, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_EqualEqual_StriStri_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_ExecuteUbergraph_W_Friend, CallFunc_BooleanOR_ReturnValue_3) == 0x0000B2, "Member 'W_Friend_C_ExecuteUbergraph_W_Friend::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");

// Function W_Friend.W_Friend_C.BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     Button;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");
static_assert(sizeof(W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature) == 0x000010, "Wrong size on W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature");
static_assert(offsetof(W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature, bSelected) == 0x000000, "Member 'W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature::bSelected' has a wrong offset!");
static_assert(offsetof(W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature, Button) == 0x000008, "Member 'W_Friend_C_BndEvt__ButtonJoin_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature::Button' has a wrong offset!");

// Function W_Friend.W_Friend_C.Init Data
// 0x0060 (0x0060 - 0x0000)
struct W_Friend_C_Init_Data final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue;         // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetUserName_ReturnValue;                  // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool bWasSuccessful, class UTexture* ResultTexture)> K2Node_CreateDelegate_OutputDelegate; // 0x0050(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(W_Friend_C_Init_Data) == 0x000008, "Wrong alignment on W_Friend_C_Init_Data");
static_assert(sizeof(W_Friend_C_Init_Data) == 0x000060, "Wrong size on W_Friend_C_Init_Data");
static_assert(offsetof(W_Friend_C_Init_Data, Temp_bool_Variable) == 0x000000, "Member 'W_Friend_C_Init_Data::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, Temp_bool_Variable_1) == 0x000001, "Member 'W_Friend_C_Init_Data::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, CallFunc_IsValid_ReturnValue) == 0x000002, "Member 'W_Friend_C_Init_Data::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, CallFunc_GetIsPlayingThisGame_ReturnValue) == 0x000003, "Member 'W_Friend_C_Init_Data::CallFunc_GetIsPlayingThisGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, CallFunc_GetIsOnline_ReturnValue) == 0x000004, "Member 'W_Friend_C_Init_Data::CallFunc_GetIsOnline_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, CallFunc_GetUserName_ReturnValue) == 0x000008, "Member 'W_Friend_C_Init_Data::CallFunc_GetUserName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, CallFunc_Conv_StringToText_ReturnValue) == 0x000018, "Member 'W_Friend_C_Init_Data::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, K2Node_Select_Default) == 0x000030, "Member 'W_Friend_C_Init_Data::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, K2Node_Select_Default_1) == 0x000040, "Member 'W_Friend_C_Init_Data::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Init_Data, K2Node_CreateDelegate_OutputDelegate) == 0x000050, "Member 'W_Friend_C_Init_Data::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

// Function W_Friend.W_Friend_C.OnAvatarGetComplete
// 0x0098 (0x0098 - 0x0000)
struct W_Friend_C_OnAvatarGetComplete final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture*                               ResultTexture;                                     // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            K2Node_MakeStruct_SlateBrush;                      // 0x0010(0x0088)()
};
static_assert(alignof(W_Friend_C_OnAvatarGetComplete) == 0x000008, "Wrong alignment on W_Friend_C_OnAvatarGetComplete");
static_assert(sizeof(W_Friend_C_OnAvatarGetComplete) == 0x000098, "Wrong size on W_Friend_C_OnAvatarGetComplete");
static_assert(offsetof(W_Friend_C_OnAvatarGetComplete, bWasSuccessful) == 0x000000, "Member 'W_Friend_C_OnAvatarGetComplete::bWasSuccessful' has a wrong offset!");
static_assert(offsetof(W_Friend_C_OnAvatarGetComplete, ResultTexture) == 0x000008, "Member 'W_Friend_C_OnAvatarGetComplete::ResultTexture' has a wrong offset!");
static_assert(offsetof(W_Friend_C_OnAvatarGetComplete, K2Node_MakeStruct_SlateBrush) == 0x000010, "Member 'W_Friend_C_OnAvatarGetComplete::K2Node_MakeStruct_SlateBrush' has a wrong offset!");

// Function W_Friend.W_Friend_C.InitPresence
// 0x0220 (0x0220 - 0x0000)
struct W_Friend_C_InitPresence final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	bool                                          Temp_bool_Variable_1;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0028(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0050(0x0028)()
	bool                                          Temp_bool_Variable_2;                              // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_3;                              // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsOnline_ReturnValue;                  // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E[0x2];                                       // 0x007E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0080(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsOnline_ReturnValue_1;                // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_Select_Default;                             // 0x0098(0x0028)()
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue;         // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue_2;                // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2[0x2];                                       // 0x00C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x00C4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_2;                           // 0x00D4(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPresenceFactionName_ReturnValue;       // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00F8(0x0018)()
	class FString                                 CallFunc_GetPresencePlayerCount_ReturnValue;       // 0x0110(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0120(0x0018)()
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetPresenceServerName_ReturnValue;        // 0x0140(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0158(0x0018)()
	class FString                                 CallFunc_GetPresenceMapName_ReturnValue;           // 0x0170(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue_1;                    // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x0188(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x01A0(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x01E0(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01F0(0x0018)()
	class FText                                   K2Node_Select_Default_4;                           // 0x0208(0x0018)()
};
static_assert(alignof(W_Friend_C_InitPresence) == 0x000008, "Wrong alignment on W_Friend_C_InitPresence");
static_assert(sizeof(W_Friend_C_InitPresence) == 0x000220, "Wrong size on W_Friend_C_InitPresence");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_bool_Variable) == 0x000000, "Member 'W_Friend_C_InitPresence::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_text_Variable) == 0x000008, "Member 'W_Friend_C_InitPresence::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_bool_Variable_1) == 0x000020, "Member 'W_Friend_C_InitPresence::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_MakeStruct_SlateColor) == 0x000028, "Member 'W_Friend_C_InitPresence::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_MakeStruct_SlateColor_1) == 0x000050, "Member 'W_Friend_C_InitPresence::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_bool_Variable_2) == 0x000078, "Member 'W_Friend_C_InitPresence::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_bool_Variable_3) == 0x000079, "Member 'W_Friend_C_InitPresence::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_bool_Variable_4) == 0x00007A, "Member 'W_Friend_C_InitPresence::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_byte_Variable) == 0x00007B, "Member 'W_Friend_C_InitPresence::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, Temp_byte_Variable_1) == 0x00007C, "Member 'W_Friend_C_InitPresence::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetIsOnline_ReturnValue) == 0x00007D, "Member 'W_Friend_C_InitPresence::CallFunc_GetIsOnline_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_SelectColor_ReturnValue) == 0x000080, "Member 'W_Friend_C_InitPresence::CallFunc_SelectColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetIsOnline_ReturnValue_1) == 0x000090, "Member 'W_Friend_C_InitPresence::CallFunc_GetIsOnline_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_Select_Default) == 0x000098, "Member 'W_Friend_C_InitPresence::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetIsPlayingThisGame_ReturnValue) == 0x0000C0, "Member 'W_Friend_C_InitPresence::CallFunc_GetIsPlayingThisGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetIsOnline_ReturnValue_2) == 0x0000C1, "Member 'W_Friend_C_InitPresence::CallFunc_GetIsOnline_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_Select_Default_1) == 0x0000C4, "Member 'W_Friend_C_InitPresence::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_Select_Default_2) == 0x0000D4, "Member 'W_Friend_C_InitPresence::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetPresenceFactionName_ReturnValue) == 0x0000E8, "Member 'W_Friend_C_InitPresence::CallFunc_GetPresenceFactionName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_Conv_StringToText_ReturnValue) == 0x0000F8, "Member 'W_Friend_C_InitPresence::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetPresencePlayerCount_ReturnValue) == 0x000110, "Member 'W_Friend_C_InitPresence::CallFunc_GetPresencePlayerCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000120, "Member 'W_Friend_C_InitPresence::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_IsEmpty_ReturnValue) == 0x000138, "Member 'W_Friend_C_InitPresence::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetPresenceServerName_ReturnValue) == 0x000140, "Member 'W_Friend_C_InitPresence::CallFunc_GetPresenceServerName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_Select_Default_3) == 0x000150, "Member 'W_Friend_C_InitPresence::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_Conv_StringToText_ReturnValue_2) == 0x000158, "Member 'W_Friend_C_InitPresence::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_GetPresenceMapName_ReturnValue) == 0x000170, "Member 'W_Friend_C_InitPresence::CallFunc_GetPresenceMapName_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_IsEmpty_ReturnValue_1) == 0x000180, "Member 'W_Friend_C_InitPresence::CallFunc_IsEmpty_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_Conv_StringToText_ReturnValue_3) == 0x000188, "Member 'W_Friend_C_InitPresence::CallFunc_Conv_StringToText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_MakeStruct_FormatArgumentData) == 0x0001A0, "Member 'W_Friend_C_InitPresence::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_MakeArray_Array) == 0x0001E0, "Member 'W_Friend_C_InitPresence::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, CallFunc_Format_ReturnValue) == 0x0001F0, "Member 'W_Friend_C_InitPresence::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_InitPresence, K2Node_Select_Default_4) == 0x000208, "Member 'W_Friend_C_InitPresence::K2Node_Select_Default_4' has a wrong offset!");

// Function W_Friend.W_Friend_C.Get_ButtonJoin_bIsEnabled_0
// 0x0010 (0x0010 - 0x0000)
struct W_Friend_C_Get_ButtonJoin_bIsEnabled_0 final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Friend_C_Get_ButtonJoin_bIsEnabled_0) == 0x000008, "Wrong alignment on W_Friend_C_Get_ButtonJoin_bIsEnabled_0");
static_assert(sizeof(W_Friend_C_Get_ButtonJoin_bIsEnabled_0) == 0x000010, "Wrong size on W_Friend_C_Get_ButtonJoin_bIsEnabled_0");
static_assert(offsetof(W_Friend_C_Get_ButtonJoin_bIsEnabled_0, ReturnValue) == 0x000000, "Member 'W_Friend_C_Get_ButtonJoin_bIsEnabled_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_Friend_C_Get_ButtonJoin_bIsEnabled_0, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000008, "Member 'W_Friend_C_Get_ButtonJoin_bIsEnabled_0::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");

}

