#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FriendsList

#include "Basic.hpp"

#include "W_FriendsList_classes.hpp"
#include "W_FriendsList_parameters.hpp"


namespace SDK
{

// Function W_FriendsList.W_FriendsList_C.ExecuteUbergraph_W_FriendsList
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::ExecuteUbergraph_W_FriendsList(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "ExecuteUbergraph_W_FriendsList");

	Params::W_FriendsList_C_ExecuteUbergraph_W_FriendsList Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.ResetScroll
// (BlueprintCallable, BlueprintEvent)

void UW_FriendsList_C::ResetScroll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "ResetScroll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_FriendsList_C::BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UW_FriendsList_C::BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BndEvt__W_FriendsList_Button_Hover_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_FriendsList_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "PreConstruct");

	Params::W_FriendsList_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMainMenu_Button_C*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");

	Params::W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMainMenu_Button_C*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");

	Params::W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bSelected                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UMainMenu_Button_C*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature(bool bSelected, class UMainMenu_Button_C* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");

	Params::W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature Parms{};

	Parms.bSelected = bSelected;
	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.OnFriendSessionFound
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FBlueprintSessionResult&   SessionResult                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UW_FriendsList_C::OnFriendSessionFound(const struct FBlueprintSessionResult& SessionResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "OnFriendSessionFound");

	Params::W_FriendsList_C_OnFriendSessionFound Parms{};

	Parms.SessionResult = std::move(SessionResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.HandleRequestJoin
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class USQOnlineServicesFriendUser*      FriendUser                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::HandleRequestJoin(class USQOnlineServicesFriendUser* FriendUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "HandleRequestJoin");

	Params::W_FriendsList_C_HandleRequestJoin Parms{};

	Parms.FriendUser = FriendUser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_FriendsList_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.ShowCachedFriends
// (BlueprintCallable, BlueprintEvent)

void UW_FriendsList_C::ShowCachedFriends()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "ShowCachedFriends");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.BP_OnUpdateFriendPresence
// (Event, Public, BlueprintEvent)
// Parameters:
// const class USQOnlineServicesFriendUser*FriendUser                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::BP_OnUpdateFriendPresence(const class USQOnlineServicesFriendUser* FriendUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BP_OnUpdateFriendPresence");

	Params::W_FriendsList_C_BP_OnUpdateFriendPresence Parms{};

	Parms.FriendUser = FriendUser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.BP_OnUpdateFriendsListComplete
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class USQOnlineServicesFriendUser*>&Results                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_FriendsList_C::BP_OnUpdateFriendsListComplete(const TArray<class USQOnlineServicesFriendUser*>& Results, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "BP_OnUpdateFriendsListComplete");

	Params::W_FriendsList_C_BP_OnUpdateFriendsListComplete Parms{};

	Parms.Results = std::move(Results);
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.AddFriendToList
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVerticalBox*                     List                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::AddFriendToList(class UVerticalBox* List, class UWidget* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "AddFriendToList");

	Params::W_FriendsList_C_AddFriendToList Parms{};

	Parms.List = List;
	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.ClearAllFriends
// (Public, BlueprintCallable, BlueprintEvent)

void UW_FriendsList_C::ClearAllFriends()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "ClearAllFriends");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_FriendsList.W_FriendsList_C.GetText_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UW_FriendsList_C::GetText_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "GetText_0");

	Params::W_FriendsList_C_GetText_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_FriendsList.W_FriendsList_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UW_FriendsList_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "GetVisibility_0");

	Params::W_FriendsList_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function W_FriendsList.W_FriendsList_C.HandleFriendPresenceChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UW_Friend_C*                      FriendWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::HandleFriendPresenceChanged(class UW_Friend_C* FriendWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "HandleFriendPresenceChanged");

	Params::W_FriendsList_C_HandleFriendPresenceChanged Parms{};

	Parms.FriendWidget = FriendWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_FriendsList.W_FriendsList_C.PopulateFriendsListByIndividual
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USQOnlineServicesFriendUser*      OnlineUser                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_FriendsList_C::PopulateFriendsListByIndividual(class USQOnlineServicesFriendUser* OnlineUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_FriendsList_C", "PopulateFriendsListByIndividual");

	Params::W_FriendsList_C_PopulateFriendsListByIndividual Parms{};

	Parms.OnlineUser = OnlineUser;

	UObject::ProcessEvent(Func, &Parms);
}

}

