#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FriendsList

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "OnlineSubsystemUtils_structs.hpp"


namespace SDK::Params
{

// Function W_FriendsList.W_FriendsList_C.ExecuteUbergraph_W_FriendsList
// 0x0250 (0x0250 - 0x0000)
struct W_FriendsList_C_ExecuteUbergraph_W_FriendsList final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x001E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F[0x1];                                       // 0x001F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_2;                             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_3;                             // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_4;                              // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_4;                             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_5;                             // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class USQOnlineServicesFriendUser*>    K2Node_Event_Results;                              // 0x0040(0x0010)(ConstParm, ReferenceParm)
	bool                                          K2Node_Event_bWasSuccessful;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	const class USQOnlineServicesFriendUser*      K2Node_Event_FriendUser;                           // 0x0058(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQFriendEntryWidget*                   CallFunc_Map_Find_Value;                           // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_Friend_C*                            K2Node_DynamicCast_AsW_Friend;                     // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USQOnlineServicesFriendUser*            K2Node_CustomEvent_FriendUser;                     // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBlueprintSessionResult                K2Node_CustomEvent_SessionResult;                  // 0x0098(0x0108)(ConstParm)
	TDelegate<void(const struct FBlueprintSessionResult& SessionResult)> K2Node_CreateDelegate_OutputDelegate; // 0x01A0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_5;                              // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B1[0x3];                                      // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FBlueprintSessionResult& SessionResult)> K2Node_CreateDelegate_OutputDelegate_1; // 0x01B4(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_ComponentBoundEvent_bSelected_2;            // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     K2Node_ComponentBoundEvent_Button_2;               // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bSelected_1;            // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     K2Node_ComponentBoundEvent_Button_1;               // 0x01D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x01E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x01E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E2[0x2];                                      // 0x01E2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_2;                           // 0x01E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default_3;                           // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bSelected;              // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     K2Node_ComponentBoundEvent_Button;                 // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_4;                           // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F9[0x3];                                      // 0x01F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_5;                           // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0218(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x021C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21D[0x3];                                      // 0x021D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0220(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0224(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesFriendUser*            CallFunc_Array_Get_Item;                           // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesSubsystem*             CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_SquadGameInstance_C*                K2Node_DynamicCast_AsBP_Squad_Game_Instance;       // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList) == 0x000008, "Wrong alignment on W_FriendsList_C_ExecuteUbergraph_W_FriendsList");
static_assert(sizeof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList) == 0x000250, "Wrong size on W_FriendsList_C_ExecuteUbergraph_W_FriendsList");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, EntryPoint) == 0x000000, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000008, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable) == 0x000010, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_IsValid_ReturnValue) == 0x000011, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Array_Length_ReturnValue) == 0x000014, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable) == 0x000018, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable_1) == 0x000019, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable_2) == 0x00001A, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable_1) == 0x00001B, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable_3) == 0x00001C, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable_4) == 0x00001D, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable_2) == 0x00001E, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable) == 0x000020, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable_1) == 0x000024, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable_3) == 0x000028, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable_2) == 0x00002C, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable_3) == 0x000030, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable_3' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable_4) == 0x000034, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable_4) == 0x000038, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable_4' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_float_Variable_5) == 0x00003C, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_float_Variable_5' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Event_Results) == 0x000040, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Event_Results' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Event_bWasSuccessful) == 0x000050, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Event_bWasSuccessful' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Event_FriendUser) == 0x000058, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Event_FriendUser' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x000060, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Map_Find_Value) == 0x000068, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Map_Find_ReturnValue) == 0x000070, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_DynamicCast_AsW_Friend) == 0x000078, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_DynamicCast_AsW_Friend' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_DynamicCast_bSuccess) == 0x000080, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_CustomEvent_FriendUser) == 0x000088, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_CustomEvent_FriendUser' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_byte_Variable_5) == 0x000090, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_CustomEvent_SessionResult) == 0x000098, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_CustomEvent_SessionResult' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_CreateDelegate_OutputDelegate) == 0x0001A0, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_bool_Variable_5) == 0x0001B0, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_CreateDelegate_OutputDelegate_1) == 0x0001B4, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_bSelected_2) == 0x0001C4, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_bSelected_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_Button_2) == 0x0001C8, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_Button_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_bSelected_1) == 0x0001D0, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_bSelected_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_Button_1) == 0x0001D8, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default) == 0x0001E0, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default_1) == 0x0001E1, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default_2) == 0x0001E4, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default_3) == 0x0001E8, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_bSelected) == 0x0001EC, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_bSelected' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_ComponentBoundEvent_Button) == 0x0001F0, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default_4) == 0x0001F8, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Select_Default_5) == 0x0001FC, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_Event_IsDesignTime) == 0x000200, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_PlayAnimationReverse_ReturnValue) == 0x000208, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_PlayAnimationReverse_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_PlayAnimationForward_ReturnValue) == 0x000210, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_PlayAnimationForward_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_int_Loop_Counter_Variable) == 0x000218, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Less_IntInt_ReturnValue) == 0x00021C, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Add_IntInt_ReturnValue) == 0x000220, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, Temp_int_Array_Index_Variable) == 0x000224, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_Array_Get_Item) == 0x000228, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_GetGameInstance_ReturnValue) == 0x000230, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, CallFunc_GetGameInstanceSubsystem_ReturnValue_2) == 0x000238, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::CallFunc_GetGameInstanceSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_DynamicCast_AsBP_Squad_Game_Instance) == 0x000240, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_DynamicCast_AsBP_Squad_Game_Instance' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_ExecuteUbergraph_W_FriendsList, K2Node_DynamicCast_bSuccess_1) == 0x000248, "Member 'W_FriendsList_C_ExecuteUbergraph_W_FriendsList::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_FriendsList_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_FriendsList_C_PreConstruct) == 0x000001, "Wrong alignment on W_FriendsList_C_PreConstruct");
static_assert(sizeof(W_FriendsList_C_PreConstruct) == 0x000001, "Wrong size on W_FriendsList_C_PreConstruct");
static_assert(offsetof(W_FriendsList_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'W_FriendsList_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     Button;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");
static_assert(sizeof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature) == 0x000010, "Wrong size on W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature, bSelected) == 0x000000, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature::bSelected' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature, Button) == 0x000008, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_OfflineTab_K2Node_ComponentBoundEvent_4_OnClicked__DelegateSignature::Button' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     Button;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");
static_assert(sizeof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature) == 0x000010, "Wrong size on W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature, bSelected) == 0x000000, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature::bSelected' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature, Button) == 0x000008, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_OnlineTab_1_K2Node_ComponentBoundEvent_3_OnClicked__DelegateSignature::Button' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature final
{
public:
	bool                                          bSelected;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenu_Button_C*                     Button;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature) == 0x000008, "Wrong alignment on W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");
static_assert(sizeof(W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature) == 0x000010, "Wrong size on W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature, bSelected) == 0x000000, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature::bSelected' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature, Button) == 0x000008, "Member 'W_FriendsList_C_BndEvt__W_FriendsList_Button_InGameTab_K2Node_ComponentBoundEvent_2_OnClicked__DelegateSignature::Button' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.OnFriendSessionFound
// 0x0108 (0x0108 - 0x0000)
struct W_FriendsList_C_OnFriendSessionFound final
{
public:
	struct FBlueprintSessionResult                SessionResult;                                     // 0x0000(0x0108)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(W_FriendsList_C_OnFriendSessionFound) == 0x000008, "Wrong alignment on W_FriendsList_C_OnFriendSessionFound");
static_assert(sizeof(W_FriendsList_C_OnFriendSessionFound) == 0x000108, "Wrong size on W_FriendsList_C_OnFriendSessionFound");
static_assert(offsetof(W_FriendsList_C_OnFriendSessionFound, SessionResult) == 0x000000, "Member 'W_FriendsList_C_OnFriendSessionFound::SessionResult' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.HandleRequestJoin
// 0x0008 (0x0008 - 0x0000)
struct W_FriendsList_C_HandleRequestJoin final
{
public:
	class USQOnlineServicesFriendUser*            FriendUser;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_HandleRequestJoin) == 0x000008, "Wrong alignment on W_FriendsList_C_HandleRequestJoin");
static_assert(sizeof(W_FriendsList_C_HandleRequestJoin) == 0x000008, "Wrong size on W_FriendsList_C_HandleRequestJoin");
static_assert(offsetof(W_FriendsList_C_HandleRequestJoin, FriendUser) == 0x000000, "Member 'W_FriendsList_C_HandleRequestJoin::FriendUser' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.BP_OnUpdateFriendPresence
// 0x0008 (0x0008 - 0x0000)
struct W_FriendsList_C_BP_OnUpdateFriendPresence final
{
public:
	const class USQOnlineServicesFriendUser*      FriendUser;                                        // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_BP_OnUpdateFriendPresence) == 0x000008, "Wrong alignment on W_FriendsList_C_BP_OnUpdateFriendPresence");
static_assert(sizeof(W_FriendsList_C_BP_OnUpdateFriendPresence) == 0x000008, "Wrong size on W_FriendsList_C_BP_OnUpdateFriendPresence");
static_assert(offsetof(W_FriendsList_C_BP_OnUpdateFriendPresence, FriendUser) == 0x000000, "Member 'W_FriendsList_C_BP_OnUpdateFriendPresence::FriendUser' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.BP_OnUpdateFriendsListComplete
// 0x0018 (0x0018 - 0x0000)
struct W_FriendsList_C_BP_OnUpdateFriendsListComplete final
{
public:
	TArray<class USQOnlineServicesFriendUser*>    Results;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          bWasSuccessful;                                    // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_FriendsList_C_BP_OnUpdateFriendsListComplete) == 0x000008, "Wrong alignment on W_FriendsList_C_BP_OnUpdateFriendsListComplete");
static_assert(sizeof(W_FriendsList_C_BP_OnUpdateFriendsListComplete) == 0x000018, "Wrong size on W_FriendsList_C_BP_OnUpdateFriendsListComplete");
static_assert(offsetof(W_FriendsList_C_BP_OnUpdateFriendsListComplete, Results) == 0x000000, "Member 'W_FriendsList_C_BP_OnUpdateFriendsListComplete::Results' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_BP_OnUpdateFriendsListComplete, bWasSuccessful) == 0x000010, "Member 'W_FriendsList_C_BP_OnUpdateFriendsListComplete::bWasSuccessful' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.AddFriendToList
// 0x0028 (0x0028 - 0x0000)
struct W_FriendsList_C_AddFriendToList final
{
public:
	class UVerticalBox*                           List;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                Content;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelWidget*                           CallFunc_GetParent_ReturnValue;                    // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_AddFriendToList) == 0x000008, "Wrong alignment on W_FriendsList_C_AddFriendToList");
static_assert(sizeof(W_FriendsList_C_AddFriendToList) == 0x000028, "Wrong size on W_FriendsList_C_AddFriendToList");
static_assert(offsetof(W_FriendsList_C_AddFriendToList, List) == 0x000000, "Member 'W_FriendsList_C_AddFriendToList::List' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_AddFriendToList, Content) == 0x000008, "Member 'W_FriendsList_C_AddFriendToList::Content' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_AddFriendToList, CallFunc_GetParent_ReturnValue) == 0x000010, "Member 'W_FriendsList_C_AddFriendToList::CallFunc_GetParent_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_AddFriendToList, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000018, "Member 'W_FriendsList_C_AddFriendToList::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_AddFriendToList, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x000020, "Member 'W_FriendsList_C_AddFriendToList::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.GetText_0
// 0x0038 (0x0038 - 0x0000)
struct W_FriendsList_C_GetText_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0020(0x0018)()
};
static_assert(alignof(W_FriendsList_C_GetText_0) == 0x000008, "Wrong alignment on W_FriendsList_C_GetText_0");
static_assert(sizeof(W_FriendsList_C_GetText_0) == 0x000038, "Wrong size on W_FriendsList_C_GetText_0");
static_assert(offsetof(W_FriendsList_C_GetText_0, ReturnValue) == 0x000000, "Member 'W_FriendsList_C_GetText_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetText_0, CallFunc_GetChildrenCount_ReturnValue) == 0x000018, "Member 'W_FriendsList_C_GetText_0::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetText_0, CallFunc_Conv_IntToText_ReturnValue) == 0x000020, "Member 'W_FriendsList_C_GetText_0::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.GetVisibility_0
// 0x000C (0x000C - 0x0000)
struct W_FriendsList_C_GetVisibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_GetVisibility_0) == 0x000004, "Wrong alignment on W_FriendsList_C_GetVisibility_0");
static_assert(sizeof(W_FriendsList_C_GetVisibility_0) == 0x00000C, "Wrong size on W_FriendsList_C_GetVisibility_0");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, ReturnValue) == 0x000000, "Member 'W_FriendsList_C_GetVisibility_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, Temp_bool_Variable) == 0x000001, "Member 'W_FriendsList_C_GetVisibility_0::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, Temp_byte_Variable) == 0x000002, "Member 'W_FriendsList_C_GetVisibility_0::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, Temp_byte_Variable_1) == 0x000003, "Member 'W_FriendsList_C_GetVisibility_0::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, CallFunc_GetChildrenCount_ReturnValue) == 0x000004, "Member 'W_FriendsList_C_GetVisibility_0::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000008, "Member 'W_FriendsList_C_GetVisibility_0::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_GetVisibility_0, K2Node_Select_Default) == 0x000009, "Member 'W_FriendsList_C_GetVisibility_0::K2Node_Select_Default' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.HandleFriendPresenceChanged
// 0x0020 (0x0020 - 0x0000)
struct W_FriendsList_C_HandleFriendPresenceChanged final
{
public:
	class UW_Friend_C*                            FriendWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesFriendUser*            CurrentFriend;                                     // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Friend_C*                            CurrentFriendWidget;                               // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue;         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue;                  // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_FriendsList_C_HandleFriendPresenceChanged) == 0x000008, "Wrong alignment on W_FriendsList_C_HandleFriendPresenceChanged");
static_assert(sizeof(W_FriendsList_C_HandleFriendPresenceChanged) == 0x000020, "Wrong size on W_FriendsList_C_HandleFriendPresenceChanged");
static_assert(offsetof(W_FriendsList_C_HandleFriendPresenceChanged, FriendWidget) == 0x000000, "Member 'W_FriendsList_C_HandleFriendPresenceChanged::FriendWidget' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_HandleFriendPresenceChanged, CurrentFriend) == 0x000008, "Member 'W_FriendsList_C_HandleFriendPresenceChanged::CurrentFriend' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_HandleFriendPresenceChanged, CurrentFriendWidget) == 0x000010, "Member 'W_FriendsList_C_HandleFriendPresenceChanged::CurrentFriendWidget' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_HandleFriendPresenceChanged, CallFunc_GetIsPlayingThisGame_ReturnValue) == 0x000018, "Member 'W_FriendsList_C_HandleFriendPresenceChanged::CallFunc_GetIsPlayingThisGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_HandleFriendPresenceChanged, CallFunc_GetIsOnline_ReturnValue) == 0x000019, "Member 'W_FriendsList_C_HandleFriendPresenceChanged::CallFunc_GetIsOnline_ReturnValue' has a wrong offset!");

// Function W_FriendsList.W_FriendsList_C.PopulateFriendsListByIndividual
// 0x0040 (0x0040 - 0x0000)
struct W_FriendsList_C_PopulateFriendsListByIndividual final
{
public:
	class USQOnlineServicesFriendUser*            OnlineUser;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USQOnlineServicesFriendUser*            CurrentFriend;                                     // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Friend_C*                            CurrentFriendWidget;                               // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UpdateCachedPresence_ReturnValue;         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class USQOnlineServicesFriendUser* FriendUser)> K2Node_CreateDelegate_OutputDelegate; // 0x001C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_GetIsPlayingThisGame_ReturnValue;         // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsOnline_ReturnValue;                  // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E[0x2];                                       // 0x002E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_Friend_C*                            CallFunc_Create_ReturnValue;                       // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FriendsList_C_PopulateFriendsListByIndividual) == 0x000008, "Wrong alignment on W_FriendsList_C_PopulateFriendsListByIndividual");
static_assert(sizeof(W_FriendsList_C_PopulateFriendsListByIndividual) == 0x000040, "Wrong size on W_FriendsList_C_PopulateFriendsListByIndividual");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, OnlineUser) == 0x000000, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::OnlineUser' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CurrentFriend) == 0x000008, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CurrentFriend' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CurrentFriendWidget) == 0x000010, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CurrentFriendWidget' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CallFunc_UpdateCachedPresence_ReturnValue) == 0x000018, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CallFunc_UpdateCachedPresence_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, K2Node_CreateDelegate_OutputDelegate) == 0x00001C, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CallFunc_GetIsPlayingThisGame_ReturnValue) == 0x00002C, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CallFunc_GetIsPlayingThisGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CallFunc_GetIsOnline_ReturnValue) == 0x00002D, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CallFunc_GetIsOnline_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CallFunc_GetOwningPlayer_ReturnValue) == 0x000030, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_FriendsList_C_PopulateFriendsListByIndividual, CallFunc_Create_ReturnValue) == 0x000038, "Member 'W_FriendsList_C_PopulateFriendsListByIndividual::CallFunc_Create_ReturnValue' has a wrong offset!");

}

