#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_NotificationPanel

#include "Basic.hpp"

#include "Squad_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Slate_structs.hpp"
#include "S_MainNotification_structs.hpp"


namespace SDK::Params
{

// Function W_NotificationPanel.W_NotificationPanel_C.ExecuteUbergraph_W_NotificationPanel
// 0x01B8 (0x01B8 - 0x0000)
struct W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               K2Node_MakeStruct_Anchors;                         // 0x0004(0x0010)(NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_Message_1;                      // 0x0030(0x0018)()
	ESQNotificationTypes                          K2Node_CustomEvent_Type;                           // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_CustomEvent_Custom_Icon;                    // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_CustomEvent_CustomIconColor;                // 0x0058(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_PreventRepetition;              // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_PlayerName;                     // 0x0070(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Message;                        // 0x0080(0x0010)(ConstParm, ZeroConstructor, HasGetValueTypeHash)
	ESQChat                                       K2Node_CustomEvent_Channel;                        // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_CustomEvent_Color;                          // 0x0094(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESQNotificationTypes                          K2Node_CustomEvent_NotificationType;               // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A5[0x3];                                       // 0x00A5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x00A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BA[0x6];                                       // 0x00BA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue;                          // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_ED[0x3];                                       // 0x00ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& PlayerName, const class FString& Message, ESQChat Channel, const struct FLinearColor& Color, ESQNotificationTypes NotificationType)> K2Node_CreateDelegate_OutputDelegate_1; // 0x00F0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Select_Default;                             // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0120(0x0018)()
	struct FLinearColor                           Temp_struct_Variable_1;                            // 0x0138(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_149[0x7];                                      // 0x0149(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_MainNotification_C*                  CallFunc_Create_ReturnValue;                       // 0x0150(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           K2Node_Select_Default_1;                           // 0x0158(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FS_MainNotification                    K2Node_MakeStruct_S_MainNotification;              // 0x0168(0x0028)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASQHUD*                                 K2Node_DynamicCast_AsSQHUD;                        // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel) == 0x000008, "Wrong alignment on W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel");
static_assert(sizeof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel) == 0x0001B8, "Wrong size on W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, EntryPoint) == 0x000000, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_MakeStruct_Anchors) == 0x000004, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_MakeStruct_Anchors' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_IsValid_ReturnValue) == 0x000014, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, Temp_bool_Variable) == 0x000028, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Message_1) == 0x000030, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Message_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Type) == 0x000048, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Type' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Custom_Icon) == 0x000050, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Custom_Icon' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_CustomIconColor) == 0x000058, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_CustomIconColor' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_PreventRepetition) == 0x000068, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_PreventRepetition' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_PlayerName) == 0x000070, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_PlayerName' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Message) == 0x000080, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Message' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Channel) == 0x000090, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Channel' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_Color) == 0x000094, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_Color' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CustomEvent_NotificationType) == 0x0000A4, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CustomEvent_NotificationType' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, Temp_struct_Variable) == 0x0000A8, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000B8, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000B9, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Concat_StrStr_ReturnValue) == 0x0000C0, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_BooleanOR_ReturnValue) == 0x0000D0, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0000D8, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Len_ReturnValue) == 0x0000E8, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x0000EC, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000F0, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_BooleanOR_ReturnValue_1) == 0x000100, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_Select_Default) == 0x000108, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000118, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Conv_StringToText_ReturnValue) == 0x000120, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, Temp_struct_Variable_1) == 0x000138, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, Temp_bool_Variable_1) == 0x000148, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Create_ReturnValue) == 0x000150, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_Select_Default_1) == 0x000158, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_MakeStruct_S_MainNotification) == 0x000168, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_MakeStruct_S_MainNotification' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_Array_Add_ReturnValue) == 0x000190, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_GetOwningPlayer_ReturnValue) == 0x000198, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, CallFunc_GetHUD_ReturnValue) == 0x0001A0, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_DynamicCast_AsSQHUD) == 0x0001A8, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_DynamicCast_AsSQHUD' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel, K2Node_DynamicCast_bSuccess) == 0x0001B0, "Member 'W_NotificationPanel_C_ExecuteUbergraph_W_NotificationPanel::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function W_NotificationPanel.W_NotificationPanel_C.Add New Chat
// 0x0038 (0x0038 - 0x0000)
struct W_NotificationPanel_C_Add_New_Chat final
{
public:
	class FString                                 PlayerName;                                        // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Message;                                           // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESQChat                                       Channel;                                           // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Color;                                             // 0x0024(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESQNotificationTypes                          NotificationType;                                  // 0x0034(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_NotificationPanel_C_Add_New_Chat) == 0x000008, "Wrong alignment on W_NotificationPanel_C_Add_New_Chat");
static_assert(sizeof(W_NotificationPanel_C_Add_New_Chat) == 0x000038, "Wrong size on W_NotificationPanel_C_Add_New_Chat");
static_assert(offsetof(W_NotificationPanel_C_Add_New_Chat, PlayerName) == 0x000000, "Member 'W_NotificationPanel_C_Add_New_Chat::PlayerName' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Add_New_Chat, Message) == 0x000010, "Member 'W_NotificationPanel_C_Add_New_Chat::Message' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Add_New_Chat, Channel) == 0x000020, "Member 'W_NotificationPanel_C_Add_New_Chat::Channel' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Add_New_Chat, Color) == 0x000024, "Member 'W_NotificationPanel_C_Add_New_Chat::Color' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Add_New_Chat, NotificationType) == 0x000034, "Member 'W_NotificationPanel_C_Add_New_Chat::NotificationType' has a wrong offset!");

// Function W_NotificationPanel.W_NotificationPanel_C.New Notification
// 0x0040 (0x0040 - 0x0000)
struct W_NotificationPanel_C_New_Notification final
{
public:
	class FText                                   Message;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	ESQNotificationTypes                          Type;                                              // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Custom_Icon;                                       // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CustomIconColor;                                   // 0x0028(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PreventRepetition;                                 // 0x0038(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_NotificationPanel_C_New_Notification) == 0x000008, "Wrong alignment on W_NotificationPanel_C_New_Notification");
static_assert(sizeof(W_NotificationPanel_C_New_Notification) == 0x000040, "Wrong size on W_NotificationPanel_C_New_Notification");
static_assert(offsetof(W_NotificationPanel_C_New_Notification, Message) == 0x000000, "Member 'W_NotificationPanel_C_New_Notification::Message' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_New_Notification, Type) == 0x000018, "Member 'W_NotificationPanel_C_New_Notification::Type' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_New_Notification, Custom_Icon) == 0x000020, "Member 'W_NotificationPanel_C_New_Notification::Custom_Icon' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_New_Notification, CustomIconColor) == 0x000028, "Member 'W_NotificationPanel_C_New_Notification::CustomIconColor' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_New_Notification, PreventRepetition) == 0x000038, "Member 'W_NotificationPanel_C_New_Notification::PreventRepetition' has a wrong offset!");

// Function W_NotificationPanel.W_NotificationPanel_C.Draw Notification
// 0x00D0 (0x00D0 - 0x0000)
struct W_NotificationPanel_C_Draw_Notification final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	ESQNotificationTypes                          Type;                                              // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Custom_Icon;                                       // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CustomIconColor;                                   // 0x0028(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PreventRepetition;                                 // 0x0038(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_NotificationItem_C*                  CallFunc_Create_ReturnValue;                       // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_NotificationItem_C*                  K2Node_DynamicCast_AsW_Notification_Item;          // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue_1;                 // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue_1;           // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_NotificationItem_C*                  K2Node_DynamicCast_AsW_Notification_Item_1;        // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x3];                                       // 0x0099(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x00A8(0x0018)()
	bool                                          CallFunc_EqualEqual_TextText_ReturnValue;          // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UVerticalBoxSlot*                       CallFunc_AddChildToVerticalBox_ReturnValue;        // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_NotificationPanel_C_Draw_Notification) == 0x000008, "Wrong alignment on W_NotificationPanel_C_Draw_Notification");
static_assert(sizeof(W_NotificationPanel_C_Draw_Notification) == 0x0000D0, "Wrong size on W_NotificationPanel_C_Draw_Notification");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, Text) == 0x000000, "Member 'W_NotificationPanel_C_Draw_Notification::Text' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, Type) == 0x000018, "Member 'W_NotificationPanel_C_Draw_Notification::Type' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, Custom_Icon) == 0x000020, "Member 'W_NotificationPanel_C_Draw_Notification::Custom_Icon' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CustomIconColor) == 0x000028, "Member 'W_NotificationPanel_C_Draw_Notification::CustomIconColor' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, PreventRepetition) == 0x000038, "Member 'W_NotificationPanel_C_Draw_Notification::PreventRepetition' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_TextIsEmpty_ReturnValue) == 0x000039, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, Temp_int_Variable) == 0x00003C, "Member 'W_NotificationPanel_C_Draw_Notification::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Create_ReturnValue) == 0x000048, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, Temp_int_Variable_1) == 0x000050, "Member 'W_NotificationPanel_C_Draw_Notification::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_GetChildrenCount_ReturnValue) == 0x000054, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_GetChildAt_ReturnValue) == 0x000058, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_GetChildAt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, K2Node_DynamicCast_AsW_Notification_Item) == 0x000068, "Member 'W_NotificationPanel_C_Draw_Notification::K2Node_DynamicCast_AsW_Notification_Item' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, K2Node_DynamicCast_bSuccess) == 0x000070, "Member 'W_NotificationPanel_C_Draw_Notification::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Subtract_IntInt_ReturnValue) == 0x000074, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000078, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Add_IntInt_ReturnValue_1) == 0x00007C, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_GetChildAt_ReturnValue_1) == 0x000080, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_GetChildAt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_GetChildrenCount_ReturnValue_1) == 0x000088, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_GetChildrenCount_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, K2Node_DynamicCast_AsW_Notification_Item_1) == 0x000090, "Member 'W_NotificationPanel_C_Draw_Notification::K2Node_DynamicCast_AsW_Notification_Item_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, K2Node_DynamicCast_bSuccess_1) == 0x000098, "Member 'W_NotificationPanel_C_Draw_Notification::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_Subtract_IntInt_ReturnValue_1) == 0x00009C, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_Subtract_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x0000A0, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_GetText_ReturnValue) == 0x0000A8, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_EqualEqual_TextText_ReturnValue) == 0x0000C0, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_EqualEqual_TextText_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_NotificationPanel_C_Draw_Notification, CallFunc_AddChildToVerticalBox_ReturnValue) == 0x0000C8, "Member 'W_NotificationPanel_C_Draw_Notification::CallFunc_AddChildToVerticalBox_ReturnValue' has a wrong offset!");

}

